# Generated by Django 3.2.5 on 2022-01-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Fuel',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='tags',
        ),
        migrations.AddField(
            model_name='advert',
            name='type_fuel',
            field=models.ManyToManyField(blank=True, to='adverts.Fuel'),
        ),
    ]
