# Generated by Django 3.2.5 on 2022-01-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('adverts', '0003_auto_20220106_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
