# Generated by Django 3.2.5 on 2022-01-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_advert_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fuel',
            new_name='Brand',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='type_fuel',
        ),
        migrations.AddField(
            model_name='advert',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adverts.brand'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
