# Generated by Django 3.2.5 on 2022-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_auto_20220108_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='bezwypadkowe',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='poj_skok',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='uszkodzone',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='wariant',
        ),
        migrations.AddField(
            model_name='advert',
            name='broken',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='engine_capacity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='no_crashed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='variant',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='featured_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advert',
            name='first_owner',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='manual_auto',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], default='Manual', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='mileage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='num_of_doors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='power',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='seller',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='year_of_production',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
