# Generated by Django 3.2.5 on 2022-01-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0008_auto_20220108_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='year_of_production',
            field=models.DateField(null=True),
        ),
    ]
