# Generated by Django 3.2.5 on 2022-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0010_alter_advert_year_of_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='year_of_production',
            field=models.IntegerField(null=True),
        ),
    ]
