# Generated by Django 3.2.5 on 2022-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0012_alter_advert_manual_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='broken',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='first_owner',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='manual_auto',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='no_crashed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='num_of_doors',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='seller',
            field=models.CharField(choices=[('A', 'All'), ('D', 'Dealer'), ('P', 'Private')], max_length=200, null=True),
        ),
    ]
