# Generated by Django 3.2.5 on 2022-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0013_auto_20220110_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='num_of_doors',
            field=models.IntegerField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six')], null=True),
        ),
    ]
