# Generated by Django 3.2.5 on 2022-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0015_alter_advert_num_of_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='broken',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='first_owner',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='manual_auto',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='no_crashed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='seller',
            field=models.CharField(choices=[('All', 'All'), ('Dealer', 'Dealer'), ('Private', 'Private')], max_length=200, null=True),
        ),
    ]
