# Generated by Django 3.2.5 on 2022-01-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0016_auto_20220113_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
