# Generated by Django 3.2.5 on 2022-01-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0017_advert_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(max_length=3500, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='engine_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
