# Generated by Django 3.2.5 on 2022-01-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0017_auto_20220115_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='engine_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='num_of_doors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='year_of_production',
            field=models.IntegerField(null=True),
        ),
    ]
