# Generated by Django 3.2.5 on 2022-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0018_auto_20220119_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
