# Generated by Django 3.2.5 on 2022-01-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0019_advert_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='location',
        ),
        migrations.AddField(
            model_name='advert',
            name='location_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='location_country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
